In [3]:
import numpy as np

# 1. ARRAY CREATION
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("1. ARRAY CREATION")
print(data)

# 2. RESHAPING
reshaped = data.reshape(1, 9)
print("\n2. RESHAPED ARRAY")
print(reshaped)

# 3. INDEXING
element = data[1, 2]
print("\n3. INDEXING")
print("Element at row 2, column 3:", element)

# 4. SLICING
sliced = data[0:2, 1:3]

print("\n4. SLICING")
print("Selected rows and columns:")
print(sliced)

# 5. AGGREGATION
print("\n5. AGGREGATION")
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Standard Deviation:", round(np.std(data), 2))


# 6. NORMALIZATION
# Min-Max Normalization
normalized = (
    (data - np.min(data)) /
    (np.max(data) - np.min(data))
)
print("\n6. NORMALIZATION")
print(np.round(normalized, 2))


# 7. STANDARDIZATION
# Z-score Standardization
standardized = (
    (data - np.mean(data)) /
    np.std(data)
)
print("\n7. STANDARDIZATION")
print(np.round(standardized, 2))

# 8. MASKING
mask = data > 50
print("\n8. BOOLEAN MASKING")
print(mask)


# 9. BOOLEAN FILTERING
filtered = data[data > 50]
print("\n9. BOOLEAN FILTERING")
print("Values greater than 50:")
print(filtered)

# 10. HANDLING MISSING VALUES
missing_data = np.array([10, 20, np.nan, 40, 50])
print("\n10. MISSING VALUE HANDLING")
print("Before handling:")
print(missing_data)

# Calculate mean ignoring NaN
mean_value = np.nanmean(missing_data)

# Replace NaN with mean
missing_data[np.isnan(missing_data)] = mean_value

print("After handling:")
print(missing_data)

# 11. SORTING
unsorted_data = np.array([50, 20, 90, 10, 40])
sorted_data = np.sort(unsorted_data)
print("\n11. SORTING")
print("Before sorting:", unsorted_data)
print("After sorting:", sorted_data)

# 12. CONCATENATION

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated = np.concatenate((array1, array2))
print("\n12. CONCATENATION")
print(concatenated)

# 13. MULTIDIMENSIONAL DATA TRANSFORMATION
transformed = data * 2 + 5
print("\n13. MULTIDIMENSIONAL DATA TRANSFORMATION")
print("Original data:")
print(data)
print("Transformed data:")
print(transformed)

1. ARRAY CREATION
[[10 20 30]
 [40 50 60]
 [70 80 90]]

2. RESHAPED ARRAY
[[10 20 30 40 50 60 70 80 90]]

3. INDEXING
Element at row 2, column 3: 60

4. SLICING
Selected rows and columns:
[[20 30]
 [50 60]]

5. AGGREGATION
Sum: 450
Mean: 50.0
Minimum: 10
Maximum: 90
Standard Deviation: 25.82

6. NORMALIZATION
[[0.   0.12 0.25]
 [0.38 0.5  0.62]
 [0.75 0.88 1.  ]]

7. STANDARDIZATION
[[-1.55 -1.16 -0.77]
 [-0.39  0.    0.39]
 [ 0.77  1.16  1.55]]

8. BOOLEAN MASKING
[[False False False]
 [False False  True]
 [ True  True  True]]

9. BOOLEAN FILTERING
Values greater than 50:
[60 70 80 90]

10. MISSING VALUE HANDLING
Before handling:
[10. 20. nan 40. 50.]
After handling:
[10. 20. 30. 40. 50.]

11. SORTING
Before sorting: [50 20 90 10 40]
After sorting: [10 20 40 50 90]

12. CONCATENATION
[1 2 3 4 5 6]

13. MULTIDIMENSIONAL DATA TRANSFORMATION
Original data:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Transformed data:
[[ 25  45  65]
 [ 85 105 125]
 [145 165 185]]
